# Generated by Django 4.2.1 on 2023-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_alter_pie_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
